import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { BaseCrudService } from '../../common/dto/base-crud.service';
import { success } from '../../common/dto';
import { AftersalesWorkOrder } from './entities/aftersales-work-order.entity';

@Injectable()
export class AftersalesService extends BaseCrudService<AftersalesWorkOrder> {
  constructor(@InjectRepository(AftersalesWorkOrder) repo: Repository<AftersalesWorkOrder>) { super(repo); }

  async getDashboard() {
    return success({
      overview: { openWorkOrders: 42, scheduledRepairs: 18, partsOnOrder: 67, workshopUtilization: 82.4, avgFirstTimeFixRate: 92.3, unplannedDowntimeReduction: 68 },
      useCases: [
        { id: 'UC-AS-01', name: 'Intelligent Repair Scheduling', status: 'active', workOrdersCreated: 342, breakdownsPrevented: 89 },
        { id: 'UC-AS-02', name: 'Parts Replacement & OEM WMS', status: 'active', partsOrdered: 1245, wrongPartRate: 1.2 },
        { id: 'UC-AS-03', name: 'Workshop Resource Management', status: 'active', workshopUtilization: 82.4, technicianEfficiency: 91.5 },
        { id: 'UC-AS-04', name: 'UN R155/R156 Compliance', status: 'active', devicesCompliant: 4185, otaUpdatesVerified: 892 },
        { id: 'UC-AS-05', name: 'OEM Field Intelligence', status: 'active', oemSubscribers: 8, failureCorrelations: 2450 },
      ],
    });
  }

  // ── UC-AS-01: Intelligent Repair Scheduling from Live Telemetry ──
  async getRepairScheduling() {
    return success({
      predictiveAlerts: [
        { id: 'RA-001', vehicleId: 'V001', plate: 'DXB-7291', type: 'Tanker', component: 'Turbocharger Wastegate Actuator', dtcCode: 'P0299', severity: 'high',
          telemetry: { oilPressureKpa: 185, coolantTempC: 102, vibrationRms: 4.2, rpmAtFailure: 2200 },
          prediction: { failureProbability: 0.87, estimatedDaysToFailure: 5, confidence: 94.2 },
          scheduledRepair: { workshopId: 'WS-JAFZA-01', technicianId: 'TECH-012', scheduledDate: new Date(Date.now()+172800000), estimatedHours: 3.5, priority: 'high' },
          driverNotification: { sent: true, language: 'ar', sentAt: new Date(Date.now()-3600000) }, status: 'scheduled' },
        { id: 'RA-002', vehicleId: 'V008', plate: 'DXB-4490', type: 'Tanker', component: 'Brake Pad Assembly — Rear Axle', dtcCode: 'C0035', severity: 'medium',
          telemetry: { brakePadThicknessMm: 3.2, brakeFluidLevel: 78, absActivations: 12 },
          prediction: { failureProbability: 0.62, estimatedDaysToFailure: 14, confidence: 88.5 },
          scheduledRepair: null, status: 'monitoring' },
        { id: 'RA-003', vehicleId: 'BUS-1103', plate: 'BUS-1103', type: 'Bus', component: 'Air Suspension Compressor', dtcCode: 'U0401', severity: 'medium',
          telemetry: { suspensionPressurePsi: 85, compressorCyclesPerHour: 18, rideHeightMm: 340 },
          prediction: { failureProbability: 0.55, estimatedDaysToFailure: 21, confidence: 82.1 },
          scheduledRepair: null, status: 'monitoring' },
      ],
      metrics: { breakdownsPrevented: 89, unplannedDowntimeReductionPct: 68, avgRepairScheduleLeadDays: 4.2, vehicleLifetimeExtensionPct: 17 },
    });
  }

  // ── UC-AS-02: Parts Replacement & OEM Warehouse Integration ──
  async getPartsIntegration() {
    return success({
      partsOrders: [
        { orderId: 'PO-2026-0891', vehicleId: 'V001', component: 'Turbocharger Wastegate Actuator', partNumber: 'MAN-51.09100-7924', oemManufacturer: 'MAN Truck & Bus',
          identification: { method: 'SVG telemetry + DTC correlation', confidence: 96.8, dtcCode: 'P0299', telemetrySignature: 'boost pressure 12% below spec at 2200 RPM' },
          warehouse: { wmsSystem: 'SAP EWM', warehouseId: 'WH-JAFZA-02', inStock: true, quantity: 3, location: 'Bin A-12-04', eta: null },
          order: { status: 'confirmed', poNumber: 'PO-2026-0891', priceAed: 4250, deliveryEta: new Date(Date.now()+86400000), autoGenerated: true } },
        { orderId: 'PO-2026-0892', vehicleId: 'V008', component: 'Brake Pad Set — Rear Axle', partNumber: 'VOL-21227349', oemManufacturer: 'Volvo Trucks',
          identification: { method: 'SVG telemetry — pad thickness sensor', confidence: 98.2, telemetrySignature: 'pad thickness 3.2mm (min: 2.0mm)' },
          warehouse: { wmsSystem: 'Oracle WMS Cloud', warehouseId: 'WH-ALQ-01', inStock: true, quantity: 8, location: 'Bin C-05-02', eta: null },
          order: { status: 'pending_approval', priceAed: 1890, autoGenerated: true } },
      ],
      metrics: { wrongPartOrderRate: 1.2, previousWrongPartRate: 12.5, firstTimeFixRate: 92.3, avgPartLeadTimeDays: 1.8, partsInventoryCostReductionPct: 24 },
      wmsConnectors: [
        { system: 'SAP EWM', status: 'connected', lastSync: new Date(Date.now()-300000), warehouses: 3 },
        { system: 'Oracle WMS Cloud', status: 'connected', lastSync: new Date(Date.now()-600000), warehouses: 2 },
      ],
    });
  }

  // ── UC-AS-03: Workshop Resource Management ──
  async getWorkshopManagement() {
    return success({
      workshops: [
        { id: 'WS-JAFZA-01', name: 'JAFZA Main Workshop', location: 'Jebel Ali Free Zone', bays: 12, baysOccupied: 9, occupancyPct: 75,
          technicians: [
            { id: 'TECH-012', name: 'Ibrahim Al-Farsi', skills: ['Engine','Turbo','HAZMAT Tanker'], certifications: ['MAN Certified','NCEMA HAZMAT'], status: 'busy', currentJob: 'V001 — Turbo Repair' },
            { id: 'TECH-015', name: 'Ravi Krishnan', skills: ['Brakes','Suspension','Electrical'], certifications: ['Volvo Certified'], status: 'available' },
            { id: 'TECH-018', name: 'Ali Mohammed', skills: ['General','Oil Change','Filters'], certifications: [], status: 'busy', currentJob: 'V022 — Scheduled Service' },
          ],
          queueDepth: 4, avgRepairHours: 3.2 },
        { id: 'WS-ALQ-01', name: 'Al Quoz Service Center', location: 'Al Quoz Industrial Area 3', bays: 8, baysOccupied: 7, occupancyPct: 87.5,
          technicians: [
            { id: 'TECH-022', name: 'Khalid Nasser', skills: ['EV Battery','Charging Systems','High Voltage'], certifications: ['ABB EV Certified'], status: 'busy' },
            { id: 'TECH-025', name: 'Mohammed Yusuf', skills: ['Bus Systems','Air Suspension','Doors'], certifications: ['Volvo Bus Certified'], status: 'available' },
          ],
          queueDepth: 6, avgRepairHours: 2.8 },
      ],
      fleetUsageRatios: [
        { fleetType: 'Tanker', avgDailyHours: 14.2, avgDailyKm: 280, dutyCycleIntensity: 'high', maintenanceStrategy: 'priority_scheduling' },
        { fleetType: 'Bus', avgDailyHours: 16.8, avgDailyKm: 220, dutyCycleIntensity: 'very_high', maintenanceStrategy: 'depot_overnight' },
        { fleetType: 'Taxi', avgDailyHours: 10.5, avgDailyKm: 310, dutyCycleIntensity: 'medium', maintenanceStrategy: 'batch_off_peak' },
      ],
      metrics: { workshopUtilizationPct: 82.4, previousUtilizationPct: 65, vehicleDowntimeReductionPct: 40, technicianEfficiency: 91.5 },
    });
  }

  // ── UC-AS-04: UN R155/R156 Compliance ──
  async getCybersecurityCompliance() {
    return success({
      r155: { standard: 'UNECE R155 — Cybersecurity Management System (CSMS)', status: 'compliant', devicesCompliant: 4185, devicesTotal: 4230, compliancePct: 98.9,
        capabilities: ['TPM 2.0 hardware root of trust', 'Secure boot chain', 'FIPS 140-3 crypto', 'Blockchain SW version registry', 'End-to-end chain of custody'] },
      r156: { standard: 'UNECE R156 — Software Update Management System (SUMS)', status: 'compliant', otaUpdatesVerified: 892, rollbackProtection: true,
        auditTrail: { totalRecords: 12450, blockchainAnchored: true, immutable: true } },
      chainOfTrust: [
        { layer: 1, name: 'OEM Build Server', description: 'Cryptographic signing of SW artifact', status: 'verified' },
        { layer: 2, name: 'Blue Edge OTA Server', description: 'Artifact integrity check + blockchain record', status: 'verified' },
        { layer: 3, name: 'SVG Device — TPM 2.0', description: 'Hardware attestation + secure boot verify', status: 'verified' },
        { layer: 4, name: 'Vehicle ECU', description: 'Flash verification + version registry update', status: 'verified' },
      ],
      markets: ['UAE', 'EU (27 countries)', 'UK', 'Japan', 'South Korea', 'Australia', '54 additional UNECE contracting parties'],
      competitiveAdvantage: 'Samsara and Geotab lack hardware root of trust — cannot provide R155/R156 compliance evidence',
    });
  }

  // ── UC-AS-05: OEM Field Intelligence & Digital Passport ──
  async getOEMFieldIntelligence() {
    return success({
      fieldIntelligence: {
        failureCorrelations: [
          { component: 'Turbocharger Assembly', factor: 'Country Climate', finding: 'Fails 3.2× more in hot/humid (>45°C, >70% humidity)', vehicles: 420, confidence: 94.5 },
          { component: 'Suspension Bushings', factor: 'Road Infrastructure', finding: 'Degrades 40% faster on unpaved/poor roads', vehicles: 890, confidence: 92.1 },
          { component: 'Brake Pads', factor: 'Driver Behavior', finding: 'Aggressive driving reduces life by 55%', vehicles: 1240, confidence: 96.8 },
          { component: 'Turbo Wastegate', factor: 'Load Usage', finding: 'Overloaded tankers show 2.8× failure rate', vehicles: 180, confidence: 89.3 },
          { component: 'Cargo Seals', factor: 'Hazardous Events', finding: 'HAZMAT cargo correlates with seal degradation', vehicles: 95, confidence: 87.6 },
          { component: 'Shock Absorbers', factor: 'Road Condition', finding: 'Road roughness IRI > 6 doubles replacement frequency', vehicles: 650, confidence: 91.4 },
        ],
        correlationFactors: ['Country Climate', 'Road Infrastructure', 'Driver Behavior', 'Load Usage', 'Hazardous Events', 'Road Condition', 'Service Lifecycle', 'Digital Passport'],
      },
      digitalPassport: { vehiclesCovered: 4230, fields: ['VehicleNFT provenance', 'Full maintenance history', 'Parts genealogy', 'Software versions', 'Operational profile', 'Compliance certifications'] },
      oemSubscriptions: [
        { oem: 'MAN Truck & Bus', tier: 'Enterprise', vehiclesCovered: 1200, pricePerVehicleYear: 200, annualRevenueAed: 240000 * 3.67, dataDelivery: 'API + Dashboard + Quarterly Reports' },
        { oem: 'Volvo Trucks', tier: 'Professional', vehiclesCovered: 800, pricePerVehicleYear: 120, annualRevenueAed: 96000 * 3.67 },
        { oem: 'Hino Motors', tier: 'Basic', vehiclesCovered: 350, pricePerVehicleYear: 50, annualRevenueAed: 17500 * 3.67 },
      ],
      metrics: { oemWarrantyCostReductionPct: 18.5, totalCorrelations: 2450, activeOEMSubscribers: 8 },
    });
  }

  async createWorkOrder(dto: any) {
    return success({ workOrderId: `WO-${Date.now()}`, status: 'created', ...dto, createdAt: new Date() });
  }

  async updateWorkOrderStatus(id: string, dto: any) {
    return success({ id, ...dto, updatedAt: new Date() });
  }
}
