#!/usr/bin/env bash
# IG.4 — Orchestration Launcher
# Externalized wrapper over the IG.3 bootstrap launcher.
# No source paths are hardcoded. All bindings come from the external input schema.
# MUST delegate to IG.3 bootstrap launcher — no direct pipeline execution.
# Usage: ./orchestration_launcher.sh <orchestration_input_schema>

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
INPUT_SCHEMA="${1:-}"

[ -z "$INPUT_SCHEMA" ]  && echo "ERROR: orchestration input schema required" && exit 1
[ ! -f "$INPUT_SCHEMA" ] && echo "ERROR: schema not found: $INPUT_SCHEMA" && exit 1

parse_field() {
  grep -E "^${1}=" "$INPUT_SCHEMA" | cut -d= -f2- | tr -d '\r' || echo ""
}

RUN_ID="$(parse_field run_id)"
BASELINE_ANCHOR="$(parse_field baseline_anchor)"
BRANCH="$(parse_field branch)"
SOURCE_PATH="$(parse_field source_path)"
OUTPUT_ROOT="$(parse_field output_root)"
REFERENCE_RUN="$(parse_field reference_run)"
BOOTSTRAP_LAUNCHER="$(parse_field bootstrap_launcher)"
SOURCE_KIND="$(parse_field source.kind)"
SOURCE_BINDING="$(parse_field source.binding)"
GITHUB_MODE="$(parse_field github.mode)"
JIRA_MODE="$(parse_field jira.mode)"
RUN_MODE="$(parse_field run.mode)"
EXEC_MODE="$(parse_field execution.mode)"

echo "=== IG.4 Orchestration Launcher ==="
echo "Run ID:           $RUN_ID"
echo "Source binding:   $SOURCE_BINDING"
echo "Source kind:      $SOURCE_KIND"
echo "Bootstrap:        $BOOTSTRAP_LAUNCHER"
echo ""

# ── ORCHESTRATION VALIDATION ────────────────────────────────────────────────
FAIL=0
fail_check() { echo "  FAIL  $1"; FAIL=$((FAIL+1)); }
pass_check() { echo "  PASS  $1"; }

CURRENT_BRANCH="$(git branch --show-current)"
[ "$CURRENT_BRANCH" = "$BRANCH" ]      && pass_check "Branch: $CURRENT_BRANCH"                    || fail_check "Branch mismatch: got=$CURRENT_BRANCH expected=$BRANCH"
[ "$SOURCE_BINDING" = "EXTERNAL" ]     && pass_check "source.binding = EXTERNAL"                   || fail_check "source.binding must be EXTERNAL; got: $SOURCE_BINDING"
[ "$RUN_MODE" = "ORCHESTRATED_INGESTION" ] && pass_check "run.mode = ORCHESTRATED_INGESTION"       || fail_check "run.mode must be ORCHESTRATED_INGESTION; got: $RUN_MODE"
[ "$JIRA_MODE" = "CAPSULE" ]           && pass_check "jira.mode = CAPSULE"                         || fail_check "jira.mode must be CAPSULE; got: $JIRA_MODE"
[ "$EXEC_MODE" = "CREATE_ONLY" ]       && pass_check "execution.mode = CREATE_ONLY"                || fail_check "execution.mode must be CREATE_ONLY; got: $EXEC_MODE"
[ -f "$BOOTSTRAP_LAUNCHER" ]           && pass_check "bootstrap_launcher present"                  || fail_check "bootstrap_launcher not found: $BOOTSTRAP_LAUNCHER"
[ -x "$BOOTSTRAP_LAUNCHER" ]           && pass_check "bootstrap_launcher executable"               || fail_check "bootstrap_launcher not executable: $BOOTSTRAP_LAUNCHER"
[ -d "$SOURCE_PATH" ]                  && pass_check "source_path accessible"                      || fail_check "source_path not found: $SOURCE_PATH"
[ ! -d "$OUTPUT_ROOT" ]                && pass_check "output_root is fresh"                        || fail_check "output_root already exists: $OUTPUT_ROOT"
[ -d "$REFERENCE_RUN" ]                && pass_check "reference_run present"                       || fail_check "reference_run not found: $REFERENCE_RUN"

# Verify bootstrap launcher belongs to ig3 (no bypass)
echo "$BOOTSTRAP_LAUNCHER" | grep -q "ig3/bootstrap_launcher" && pass_check "Delegation target is IG.3 bootstrap" || fail_check "bootstrap_launcher must be scripts/pios/ig3/bootstrap_launcher.sh"

if [ "$FAIL" -gt 0 ]; then
  echo ""
  echo "ORCHESTRATION_FAIL: $FAIL checks failed — aborting"
  exit 1
fi

echo ""
echo "Orchestration checks passed. Translating schema and delegating to IG.3 bootstrap..."
echo ""

# ── TRANSLATE TO BOOTSTRAP INPUT SCHEMA ─────────────────────────────────────
BOOTSTRAP_SCHEMA="$(mktemp /tmp/ig4_bootstrap_XXXXXX.schema)"
trap "rm -f $BOOTSTRAP_SCHEMA" EXIT

cat > "$BOOTSTRAP_SCHEMA" <<BSEOF
# IG.4 → IG.3 Translated Bootstrap Schema
# Auto-generated by orchestration_launcher.sh — DO NOT EDIT

run_id=$RUN_ID
baseline_anchor=$BASELINE_ANCHOR
branch=$BRANCH
source_path=$SOURCE_PATH
output_root=$OUTPUT_ROOT
reference_run=$REFERENCE_RUN
source.kind=$SOURCE_KIND
github.mode=$GITHUB_MODE
jira.mode=$JIRA_MODE
run.mode=BOOTSTRAP_PIPELINE
execution.mode=$EXEC_MODE
BSEOF

# ── DELEGATE TO IG.3 BOOTSTRAP ───────────────────────────────────────────────
echo "Delegating to: $BOOTSTRAP_LAUNCHER"
bash "$BOOTSTRAP_LAUNCHER" "$BOOTSTRAP_SCHEMA"

# ── ANNOTATE adapter_binding.md WITH ORCHESTRATION CONTEXT ───────────────────
if [ -f "$OUTPUT_ROOT/adapter_binding.md" ]; then
  cat >> "$OUTPUT_ROOT/adapter_binding.md" <<ORCHEOF

---

## Orchestration Layer

orchestration_layer: IG.4
orchestration_run_mode: $RUN_MODE
source.binding: $SOURCE_BINDING
bootstrap_delegated_to: $(basename "$BOOTSTRAP_LAUNCHER")
orchestration_schema: $(basename "$INPUT_SCHEMA")
ORCHEOF
fi

echo ""
echo "ORCHESTRATION_COMPLETE — run_id: $RUN_ID"
