import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, Index } from 'typeorm';

/**
 * HASI Firewall Rule — Auto-generated by HASI Recommendation Engine
 * Can be deployed fleet-wide or per-device
 * Formats: iptables, Cisco ACL, Palo Alto, Fortinet, vendor-neutral
 */
@Entity('hasi_firewall_rules')
@Index(['svgDeviceId'])
@Index(['captureId'])
@Index(['status'])
@Index(['severity'])
export class HasiFirewallRule {
  @PrimaryGeneratedColumn('uuid') id: string;

  @Column({ nullable: true }) captureId: string; // originating capture
  @Column({ nullable: true }) threatId: string; // originating threat
  @Column({ nullable: true }) svgDeviceId: string; // null = fleet-wide rule

  // ── Rule Definition ──────────────────────────────────────────
  @Column({ type: 'enum', enum: ['allow', 'deny', 'drop', 'reject', 'log', 'rate_limit'], default: 'deny' })
  action: string;

  @Column({ type: 'enum', enum: ['inbound', 'outbound', 'both'], default: 'inbound' })
  direction: string;

  @Column({ length: 20, nullable: true }) protocol: string; // tcp, udp, icmp, any
  @Column({ length: 45, nullable: true }) sourceIp: string;
  @Column({ length: 5, nullable: true }) sourceMask: string;
  @Column({ length: 20, nullable: true }) sourcePort: string; // can be range e.g. "1024-65535"
  @Column({ length: 45, nullable: true }) destinationIp: string;
  @Column({ length: 5, nullable: true }) destinationMask: string;
  @Column({ length: 20, nullable: true }) destinationPort: string;

  @Column({ length: 300 }) description: string;
  @Column({ type: 'enum', enum: ['critical', 'high', 'medium', 'low'], default: 'medium' })
  severity: string;

  // ── Vendor-Specific Configs ──────────────────────────────────
  @Column({ type: 'text', nullable: true }) iptablesRule: string;
  @Column({ type: 'text', nullable: true }) ciscoAcl: string;
  @Column({ type: 'text', nullable: true }) paloAltoRule: string;
  @Column({ type: 'text', nullable: true }) fortinetRule: string;
  @Column({ type: 'text', nullable: true }) vendorNeutralRule: string;

  // ── Deployment Status ────────────────────────────────────────
  @Column({ type: 'enum', enum: ['proposed', 'approved', 'deployed', 'active', 'disabled', 'rejected', 'expired'], default: 'proposed' })
  status: string;

  @Column({ default: false }) fleetWide: boolean;
  @Column({ type: 'jsonb', nullable: true, default: () => "'[]'" }) deployedToDevices: string[]; // device IDs
  @Column({ type: 'int', default: 0 }) deployedCount: number;

  @Column({ nullable: true }) approvedBy: string;
  @Column({ nullable: true }) approvedAt: Date;
  @Column({ nullable: true }) deployedAt: Date;
  @Column({ nullable: true }) expiresAt: Date;

  // ── Effectiveness ────────────────────────────────────────────
  @Column({ type: 'int', default: 0 }) hitCount: number;
  @Column({ nullable: true }) lastHitAt: Date;

  @CreateDateColumn() createdAt: Date;
  @UpdateDateColumn() updatedAt: Date;
}
